export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST"
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS"
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL"

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST"
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS"
export const GET_BOOK_FAIL = "GET_BOOK_FAIL"

export const DELETE_BOOKS_REQUEST = "DELETE_BOOKS_REQUEST"
export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS"
export const DELETE_BOOKS_FAIL = "DELETE_BOOKS_FAIL"